version: "3"
services:
  nginx:
    image: nginx:${NGINX_VERSION}
    ports:
      - "${NGINX_HTTP_HOST_PORT}:80"
      - "${NGINX_HTTPS_HOST_PORT}:443"
    volumes:
      - ${SOURCE_DIR}:/var/www/html/:rw
      - ${NGINX_CONFD_DIR}:/etc/nginx/conf.d/:rw
      - ${NGINX_CONF_FILE}:/etc/nginx/nginx.conf:ro
      - ${NGINX_LOG_DIR}:/var/log/nginx/:rw
    environment:
      TZ: ${TZ}
    container_name: cinling_nginx
    restart: always
    networks:
      - default
#  php72:
#    image: bitnami/php-fpm:${PHP_VERSION}
#    restart: always
#    volumes:
#      - ${SOURCE_DIR}:/var/www/html/:rw
#      - ${PHP_INI_FILE}:/usr/local/etc/php/php.ini:ro
#      - ${PHP_FMP_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf:rw
#      - ${PHP_LOG_DIR}:/var/log/php
#    container_name: cinling_php-fpm
  mysql:
    image: mysql:${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DIR}:/var/lib:rw
#      - ${MYSQL_CONF_FILE}:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - default
    container_name: cinling_mysql
    restart: always
networks:
  default:
